name: COPR Build (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 0.1.1)'
        required: true
        type: string
      commit-ref:
        description: 'Git commit reference (tag, branch, or SHA)'
        required: false
        type: string
        default: 'main'

permissions:
  contents: read

env:
  PACKAGE_NAME: phonehome

jobs:
  copr-build:
    name: Submit COPR Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install COPR CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install copr-cli

      - name: Configure COPR CLI
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr << EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = ${{ secrets.COPR_USERNAME }}
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

      - name: Validate inputs and secrets
        run: |
          # Validate required variables and secrets
          if [ -z "${{ vars.COPR_PROJECT }}" ]; then
            echo "Error: COPR_PROJECT variable is not set. Should be in format 'username/projectname'"
            exit 1
          fi

          if [ -z "${{ secrets.COPR_LOGIN }}" ] || [ -z "${{ secrets.COPR_TOKEN }}" ]; then
            echo "Error: COPR authentication secrets (COPR_LOGIN, COPR_TOKEN) are not set"
            exit 1
          fi

          echo "✓ COPR project: ${{ vars.COPR_PROJECT }}"
          echo "✓ Authentication configured"

      - name: Update spec file version
        run: |
          sed -i "s/^Version:.*/Version:        ${{ inputs.version }}/" ${{ env.PACKAGE_NAME }}.spec
          echo "Updated spec file version to ${{ inputs.version }}"

      - name: Test COPR authentication
        run: |
          echo "Testing COPR authentication..."
          copr-cli whoami

      - name: Submit COPR build
        run: |
          COMMIT_REF="${{ inputs.commit-ref }}"
          
          echo "Submitting COPR build with parameters:"
          echo "  Project: ${{ vars.COPR_PROJECT }}"
          echo "  Repository: ${{ github.server_url }}/${{ github.repository }}"
          echo "  Commit: $COMMIT_REF"
          echo "  Spec file: ${{ env.PACKAGE_NAME }}.spec"
          echo "  Version: ${{ inputs.version }}"
          echo ""

          # Submit build to COPR using buildscm
          copr-cli buildscm "${{ vars.COPR_PROJECT }}" \
            --clone-url "${{ github.server_url }}/${{ github.repository }}" \
            --commit "$COMMIT_REF" \
            --spec "${{ env.PACKAGE_NAME }}.spec" \
            --nowait

      - name: Build submitted
        run: |
          echo "🎉 COPR build submitted successfully!"
          echo ""
          echo "Build details:"
          echo "  Version: ${{ inputs.version }}"
          echo "  Commit: ${{ inputs.commit-ref }}"
          echo ""
          echo "Check build status at:"
          echo "  https://copr.fedorainfracloud.org/coprs/${{ vars.COPR_PROJECT }}/builds/"