name: COPR Build

on:
  release:
    types: [published]

env:
  PACKAGE_NAME: phonehome_server

jobs:
  build-copr:
    name: Build RPM on COPR
    runs-on: ubuntu-latest

    steps:
      - name: Install COPR CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install copr-cli

      - name: Configure COPR CLI
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr << EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = ${{ secrets.COPR_USERNAME }}
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

      - name: Submit COPR build
        run: |
          # Validate required variables and secrets
          if [ -z "${{ vars.COPR_PROJECT }}" ]; then
            echo "Error: COPR_PROJECT variable is not set. Should be in format 'username/projectname'"
            exit 1
          fi

          if [ -z "${{ secrets.COPR_LOGIN }}" ] || [ -z "${{ secrets.COPR_TOKEN }}" ]; then
            echo "Error: COPR authentication secrets (COPR_LOGIN, COPR_TOKEN) are not set"
            exit 1
          fi

          # Set commit reference based on event type
          if [ "${{ github.event_name }}" = "release" ]; then
            COMMIT_REF="${{ github.event.release.tag_name }}"
          else
            COMMIT_REF="${{ github.sha }}"
          fi

          # Debug output
          echo "COPR Project: ${{ vars.COPR_PROJECT }}"
          echo "Clone URL: ${{ github.server_url }}/${{ github.repository }}"
          echo "Commit Reference: $COMMIT_REF"
          echo "Spec File: ${{ env.PACKAGE_NAME }}.spec"

          # Test COPR authentication first
          echo "Testing COPR authentication..."
          copr-cli whoami

          # Submit build to COPR using buildscm (builds directly from git repository)
          # This approach clones the git repo and builds from source, using the spec file in the repo
          echo "Submitting build to COPR..."
          copr-cli buildscm "${{ vars.COPR_PROJECT }}" \
            --clone-url "${{ github.server_url }}/${{ github.repository }}" \
            --commit "$COMMIT_REF" \
            --spec "${{ env.PACKAGE_NAME }}.spec" \
            --nowait

      - name: Comment on PR (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "COPR build submitted."
          echo "Check build status at: https://copr.fedorainfracloud.org/coprs/${{ secrets.COPR_USERNAME }}/${{ secrets.COPR_PROJECT }}/builds/"
