name: COPR Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "0.1.0"

permissions:
  contents: write # Required for uploading release assets

env:
  PACKAGE_NAME: phonehome_server

jobs:
  build-copr:
    name: Build RPM on COPR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION=${VERSION#v}  # Remove 'v' prefix if present
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Update spec file version
        run: |
          # Update version in spec file for consistency (COPR will use git content)
          sed -i "s/^Version:.*/Version:        ${{ steps.version.outputs.version }}/" ${{ env.PACKAGE_NAME }}.spec

      - name: Create source tarball
        run: |
          # Create tarball for artifacts and manual distribution (not used by COPR build)
          sed -i "s/VERSION=.*/VERSION=\"${{ steps.version.outputs.version }}\"/" make-tarball.sh
          ./make-tarball.sh

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ steps.version.outputs.version }}-source
          path: ${{ env.PACKAGE_NAME }}-${{ steps.version.outputs.version }}.tar.gz

      - name: Create release and upload tarball (if tag push)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          TARBALL_NAME="${{ env.PACKAGE_NAME }}-${{ steps.version.outputs.version }}.tar.gz"
          TAG_NAME="${{ github.ref_name }}"

          # Verify tarball exists
          if [ ! -f "$TARBALL_NAME" ]; then
            echo "Error: Tarball $TARBALL_NAME not found"
            exit 1
          fi

          echo "Creating release for tag $TAG_NAME..."
          if ! gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --notes "Automated release for $TAG_NAME" \
            "$TARBALL_NAME"; then
            echo "Failed to create release and upload tarball"
            exit 1
          fi
          echo "Release created and tarball successfully uploaded"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install COPR CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install copr-cli

      - name: Configure COPR CLI
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr << EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = ${{ secrets.COPR_USERNAME }}
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

      - name: Submit COPR build
        run: |
          # Validate required variables and secrets
          if [ -z "${{ vars.COPR_PROJECT }}" ]; then
            echo "Error: COPR_PROJECT variable is not set. Should be in format 'username/projectname'"
            exit 1
          fi

          if [ -z "${{ secrets.COPR_LOGIN }}" ] || [ -z "${{ secrets.COPR_TOKEN }}" ]; then
            echo "Error: COPR authentication secrets (COPR_LOGIN, COPR_TOKEN) are not set"
            exit 1
          fi

          # Set commit reference based on event type
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            COMMIT_REF="${{ github.ref_name }}"
          else
            COMMIT_REF="${{ github.sha }}"
          fi

          # Debug output
          echo "COPR Project: ${{ vars.COPR_PROJECT }}"
          echo "Clone URL: ${{ github.server_url }}/${{ github.repository }}"
          echo "Commit Reference: $COMMIT_REF"
          echo "Spec File: ${{ env.PACKAGE_NAME }}.spec"

          # Validate spec file exists
          if [ ! -f "${{ env.PACKAGE_NAME }}.spec" ]; then
            echo "Error: Spec file ${{ env.PACKAGE_NAME }}.spec not found in repository"
            exit 1
          fi

          # Test COPR authentication first
          echo "Testing COPR authentication..."
          copr-cli whoami

          # Validate spec file syntax
          echo "Validating spec file syntax..."
          rpmspec -P "${{ env.PACKAGE_NAME }}.spec" > /dev/null || {
            echo "Error: Spec file has syntax errors"
            exit 1
          }

          # Submit build to COPR using buildscm (builds directly from git repository)
          # This approach clones the git repo and builds from source, using the spec file in the repo
          # No Source0 tarball is needed as COPR builds directly from git
          echo "Submitting build to COPR using buildscm method..."
          copr-cli buildscm "${{ vars.COPR_PROJECT }}" \
            --clone-url "${{ github.server_url }}/${{ github.repository }}" \
            --commit "$COMMIT_REF" \
            --spec "${{ env.PACKAGE_NAME }}.spec" \
            --nowait || {
            echo "Error: COPR build submission failed"
            echo "This usually indicates a spec file issue or COPR configuration problem"
            echo "Check the spec file for Source0 references that conflict with buildscm"
            exit 1
          }
          
          echo "COPR build submitted successfully!"

      - name: Comment on PR (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "COPR build submitted for version ${{ steps.version.outputs.version }}"
          echo "Check build status at: https://copr.fedorainfracloud.org/coprs/${{ secrets.COPR_USERNAME }}/${{ secrets.COPR_PROJECT }}/builds/"
